#!/bin/sh
export CXX=/usr/bin/clang++
export CC=/usr/bin/clang

export EDITOR=nvim
export SVN_EDITOR=nvim

alias ls="ls      --color=auto"
alias ll="ls -lh  --color=auto"
alias la="ls -lha --color=auto"


