#!/bin/zsh
[ -f ~/.config/shell/aliases ] && source ~/.config/shell/aliases

## assorted configuration
setopt appendhistory 
setopt autocd

unsetopt beep 
unsetopt extendedglob

bindkey -v

## completion configuration
autoload -Uz compinit && compinit

# disable named-directories autocompletion
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories

# Use caching so that commands like apt and dpkg complete are useable
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR

## prompt configuration
autoload -Uz colors && colors
autoload -Uz promptinit && promptinit
PROMPT="%n@%m %(!.#.$) "

## shell history configuration
HISTFILE=~/.cache/zsh/history
HISTSIZE=2048
SAVEHIST=1000000
